### ISSUE TITLE
make install-tools fails on third party library

### ISSUE THREAD

**Issue by marxriedl** [go-clang/gen#107]
Local and on Travis CI during make install-tools the following error gets emitted:
```
package github.com/kisielk/errcheck/...
	imports github.com/kisielk/errcheck
	imports github.com/kisielk/errcheck/internal/errcheck
	imports go/types: unrecognized import path "go/types"

make: *** [install-tools] Error 1
```
Prevents #106

**Comment by zimmski** [comment]
The problem is that go/types in the /x repository and we had to migrate errcheck to go/types of Go 1.5. Errcheck therefore forces all users to migrate to at least 1.5. This is described in https://github.com/kisielk/errcheck/issues/89
