### ISSUE TITLE
tu.DisposeTokens() returns incorrect memory

### ISSUE THREAD

**Issue by FrankReh** [go-clang/gen#108]
I may have run into a problem with the v3.7 code.  Don't know if it is there in earlier branches because I went right to 3.7.

In trying to figure out how to parse BinaryOperator Cursors, I ran into a stackoverflow suggestion about tokenizing the cursor and iterating through the tokens to find the actual operator in question.  Kind of weird that libclang makes us do that, but okay.  (Maybe there is a more straightforward method that I haven't run into yet.)

And of course because there is an array that is allocated by libclang, it later has to be disposed.  But the tu.DisposeTokens() function causes a memory exception when I run it under a 'go test' environment, claiming the memory being returned to malloc didn't come from malloc, and in fact the DisposeTokens() code looks wrong.  It goes out of its way *not* to use the same array that had been used to underpin the slice in the first place by tu.Tokenize(), but that's the array that needs to be returned to the C heap. 

Here's a diff that seems to fix it for me.  

```diff
diff --git a/clang/translationunit_gen.go b/clang/translationunit_gen.go
index 8c3ea1b..6e4a93d 100644
--- a/clang/translationunit_gen.go
+++ b/clang/translationunit_gen.go
@@ -329,14 +329,8 @@ func (tu TranslationUnit) Tokenize(r SourceRange) []Token {
 
 // Free the given set of tokens.
 func (tu TranslationUnit) DisposeTokens(tokens []Token) {
-       ca_tokens := make([]C.CXToken, len(tokens))
-       var cp_tokens *C.CXToken
-       if len(tokens) > 0 {
-               cp_tokens = &ca_tokens[0]
-       }
-       for i := range tokens {
-               ca_tokens[i] = tokens[i].c
-       }
+       gos_tokens := (*reflect.SliceHeader)(unsafe.Pointer(&tokens))
+       cp_tokens := (*C.CXToken)(unsafe.Pointer(gos_tokens.Data))
 
        C.clang_disposeTokens(tu.c, cp_tokens, C.uint(len(tokens)))
 }
```

**Comment by marxriedl** [comment]
Thanks for the info, could you post us the memory exception please?

-marx

**Comment by FrankReh** [comment]
Here is the output from 'go test'

convert3.test(22075,0x7fff75447000) malloc: *** error for object 0xc820012900: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
