### ISSUE TITLE
Upgrade to Go 1.6 and use -msan for testing

### ISSUE THREAD

**Issue by zimmski** [go-clang/gen#113]
- Go 1.6 has stricter CGo rules
- `-msan` helps us find errors in our API

**Comment by marxriedl** [comment]
I've upgraded to Go 1.6 @ my local machine. 
After some llvm/clang shenanigans I managed to run go test/build/install with -msan option:
test gave me only output for stuff that doesn't concern us, and build/install ran without a hitch

Reading https://tip.golang.org/doc/go1.6#cgo again seems to confirm that we *should* not violate anything.

**Comment by zimmski** [comment]
I am using Go 1.7 with https://github.com/go-clang/v3.7/pull/1 so I think we can even upgrade to 1.7. The `-msan` argument should still be included though.

**Comment by zimmski** [comment]
According to https://github.com/golang/go/issues/14589 -msan can be only used with Clang >= 3.6 (I think we should include GCC in the mix)

**Comment by zimmski** [comment]
According to https://llvm.org/bugs/show_bug.cgi?id=22757 -msan cannot be used with 3.7 but I tested it with 3.6 and according to the entry it is supported by 3.8 and 3.9.

**Comment by zimmski** [comment]
According to https://github.com/golang/go/commit/eaf5235f984080d592dbc88d6e4ad4e246e2f3b2 Clang <= 3.9 does not work with Kernels >= 4.1.

**Comment by zimmski** [comment]
@sbinet do you have some experience with the address sanitizer under Go?

**Comment by zimmski** [comment]
I postet a question on the group https://groups.google.com/forum/#!topic/golang-nuts/5KkBfRR8kik

**Comment by sbinet** [comment]
nope. sorry.
