### ISSUE TITLE
HeaderFile.handle overwrites previously written code

### ISSUE THREAD

**Issue by zimmski** [go-clang/gen#136]
There are cases where additional header files add additional methods to structs which in turn overwrite the previously written version of the struct because the object/lookup tables are not shared among the HeaderFile objects.

We need to move the generation and writing code of HeaderFile.handle into a separate phase, maybe in its own struct and method. Thoughts?

**Comment by markusriedl** [comment]
is this because of #134?

**Comment by markusriedl** [comment]
could you point me to the exact location where this happens?

**Comment by zimmski** [comment]
Yes, #134 is the reason. It works by reverting that PR.

**Comment by zimmski** [comment]
https://github.com/go-clang/gen/blob/master/api.go#L47 I think

**Comment by markusriedl** [comment]
pfu, well, ah, we need a clear separation from headerfile and generation.
how exactly, dunno yet
