### ISSUE TITLE
go-clang/vX.X import path cannot be used with Go modules?

### ISSUE THREAD

**Issue by mewmew** [go-clang/gen#148]
Hi @sbinet and everyone else working on the project!

First off, I must say. Hats off, this Clang wrapper for Go is the best I've seen thus far, and even with a few workarounds I got it running on a fairly substantial code base to great results.

While importing `github.com/go-clang/v3.9/clang` it seems that this import path is incompatible with Go modules (presumably since it contains vX.X in the path). I know there are users that depends on these old import paths, but what may be a good way to make these really useful libraries also accessible to users using Go modules?

My initial suggestion would be to create a `github.com/go-clang/go-clang` repository and have it contain subdirectories, one per version (perhaps with another name than vX.X). Or, to create repositories with the following name convention `github.com/go-clang/go-clang-vX.X`. I think either of those strategies should work with Go modules.

For now I have a fork living at https://github.com/mewspring/go-clang, the only change to which is literally the name of the repository, renamed from `v3.9` to `go-clang`, and it works perfectly.

Wish you all the best and a happy start of the Autumn.

With kindness,
Robin

---

# Without modules

Without modules a `go get` of `go-clang/v3.9` works just fine.

```
$ export GOPATH=/tmp/go
$ CGO_LDFLAGS="-L`llvm-config --libdir`" go get github.com/go-clang/v3.9/...
```

# With Go modules

With Go modules, I get the error `no matching versions for query "upgrade"` when trying to `go get` `go-clang/v3.9`.

```
$ export GO111MODULE=on
$ mkdir /tmp/foo
$ cd /tmp/foo
$ go mod init foo
go: creating new go.mod: module foo
$ CGO_LDFLAGS="-L`llvm-config --libdir`" go get github.com/go-clang/v3.9/clang
go: finding github.com/go-clang/v3.9/clang latest
go get github.com/go-clang/v3.9/clang: no matching versions for query "upgrade"
```

**Comment by sbinet** [comment]
yeah... gonum had the same issue (we got a free pass on that one.)
I'll create a new clang-v3.9 repo.

**Comment by sbinet** [comment]
done. could you make sure this works for you ?

- https://github.com/go-clang/clang-v3.9

**Comment by sbinet** [comment]
(tentatively closing this one, but feel free to re-open if that didn't work for you.)

**Comment by mewmew** [comment]
Thanks @sbinet! The new import path of the repo works perfectly. I'm impressed with the quick response time, and even more so by the ambition of this project. It was exactly what I needed!

**Comment by sbinet** [comment]
it was a very simple fix :)
but I must admit I haven't been able to dedicate much time for this project...
it could do with some fresh blood...

**Comment by mewmew** [comment]
>  it could do with some fresh blood...

Haha, I would join but already got one LLVM project on my hands ^^ Btw, I know you've been on the look out for a REPL that plays nice with Go. Have you had the chance to evaluate [yaegi](https://github.com/containous/yaegi), and does it suite your needs @sbinet?

**Comment by sbinet** [comment]
> Haha, I would join but already got one LLVM project on my hands

:)

yeah, I played a bit w/ yaegi (I was actually evaluating it before it was open-sourced).
it's nice but doesn't play well with a Go installation that's on `master` and its handling of 3rd-party imports is a bit too rigid for my taste. but other than that... it's a fine project. (and it's still early days)
